### ISSUE TITLE
副图新增WR

### ISSUE THREAD

**Issue by developerjet** [octree/Stockee#1]
您好，请问副图有没有新增WR图表的打算呢。

**Comment by octree** [comment]
目前没有打算增加新的指标。
但是，Stockee 支持自定义图表的，你可以在自己项目中创建一个实现 `ChartRenderer` 协议的类即可。
可以参考：https://github.com/octree/Stockee/blob/main/Sources/Stockee/ChartRenders/Sub/KDJChart.swift
