### ISSUE TITLE
点击K线柱，如何实现展示对应K线柱详情问题。

### ISSUE THREAD

**Issue by developerjet** [octree/Stockee#2]
您好，点击K线柱，移动十字架时，如何实现展示对应K线柱详情呢。

OKX展示样式：
![WechatIMG17](https://github.com/octree/Stockee/assets/18006470/b9696aa2-631b-42c9-ae1c-74f94395af88)

**Comment by octree** [comment]
```swift
chartView.onSelect = { index in  }
```
