### ISSUE TITLE
K线极端走势导致绘制错误

### ISSUE THREAD

**Issue by developerjet** [octree/Stockee#4]
问题描述：
当极端走势时，比如涨跌过大，会导致绘制错误，超出区域。麻烦帮忙看下，谢谢了。

图一：
15分钟时区，第一根K线柱子成交数据
![Simulator Screenshot - iPhone 14 Pro - 2023-08-04 at 21 11 18](https://github.com/octree/Stockee/assets/18006470/42811c05-f3d6-4934-aa3b-3fa144532e83)

图二：
15分钟时区，第二根K线柱子成交数据
![Simulator Screenshot - iPhone 14 Pro - 2023-08-04 at 21 11 22](https://github.com/octree/Stockee/assets/18006470/6c51e8b5-a049-4120-85cb-1e4f5ba0101f)

币种k线数据json：
链接: https://pan.baidu.com/s/1Ckb3t2IFjawP1WXx0O32Hg 提取码: v5qm

**Comment by octree** [comment]
看了一下，你们服务端的数据是错误的
  - low : 0.007217
  - high : 0.008
  - open : 0.006
  - close : 0.007235

最低价比开盘价还高

**Comment by developerjet** [comment]
好的，谢谢
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月05日 11:39 |
| 收件人 | octree/Stockee ***@***.***> |
| 抄送人 | ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [octree/Stockee] K线极端走势导致绘制错误 (Issue #4) |

看了一下，你们服务端的数据是错误的

low : 0.007217
high : 0.008
open : 0.006
close : 0.007235

最低价比开盘价还高
