### ISSUE TITLE
可以支持设置空心蜡烛图吗？

### ISSUE THREAD

**Issue by LuoPengFei** [octree/Stockee#5]
你好，现在蜡烛图都是实心，大佬有计划支持空心蜡烛图吗？

**Comment by CaiShengbo** [comment]
> 你好，现在蜡烛图都是实心，大佬有计划支持空心蜡烛图吗？

我基于这个库做了一些调整以适配自己的需求，简单做了一个空心的，你可以(参考一下)[https://github.com/CaiShengbo/Stockee]。
