### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by vitasbut** [octree/Stockee#6]
Hello Octree.
I tried to use your excellent library Stockee.
But I have an issue:

when using it with SwiftUI after the deallocation of the UIViewController CharView<Candle> stayed in memory. 
This is a screenshot from the memory graph.
There is no ViewController, but CharView<Candle> with Captions and Interactions are in memory, loaded three times.

![1698060545023](https://github.com/octree/Stockee/assets/126880216/a77af40f-7351-496f-aceb-1954194a80aa)

After that, I tried to test the Demo from the package. And, unfortunately, receive memory leaks.
I added a simple UI Controller before ChartController:

![1698058162217](https://github.com/octree/Stockee/assets/126880216/1974cfae-c17d-4b9a-b291-d037905102c1)

I tapped the button and returned from the chart several times, and every time, memory allocation grew.
These are screenshots from the XCode Instruments:

![1698058342516](https://github.com/octree/Stockee/assets/126880216/98f56782-3804-438d-885d-b1515989f4dd)
![1698058416671](https://github.com/octree/Stockee/assets/126880216/68dcb5a0-c6e8-4b82-add0-7ec90d18dbef)

I am not a confident developer and can't fix it myself. 
I may have used the Package in the wrong way.

Or if it is an issue, could you help to resolve it?

**Comment by octree** [comment]
Thanks for your reporting. I will try to investigate the leak issue and fix it later.

**Comment by octree** [comment]
Fixed ce865155e04b3250c1b2a6ca8130ce636c5b6505

**Comment by vitasbut** [comment]
Thank you very much. Now everything is perfect
